"""add review context budget

Revision ID: 7d94d6e325e8
Revises: a70bb027da1a
Create Date: 2026-09-07 10:16:09.347519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d94d6e325e8'
down_revision: Union[str, Sequence[str], None] = 'a70bb027da1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_jobs_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_repository_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_review_id'), table_name='analysis_jobs')
    op.drop_constraint(op.f('analysis_jobs_repository_id_fkey'), 'analysis_jobs', type_='foreignkey')
    op.drop_constraint(op.f('analysis_jobs_review_id_fkey'), 'analysis_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'analysis_jobs', 'reviews', ['review_id'], ['id'])
    op.create_foreign_key(None, 'analysis_jobs', 'repositories', ['repository_id'], ['id'])
    op.drop_index(op.f('ix_code_embeddings_content_hash'), table_name='code_embeddings')
    op.drop_index(op.f('ix_code_embeddings_file_path'), table_name='code_embeddings')
    op.drop_index(op.f('ix_code_embeddings_id'), table_name='code_embeddings')
    op.drop_index(op.f('ix_code_embeddings_repository_id'), table_name='code_embeddings')
    op.drop_constraint(op.f('code_embeddings_repository_id_fkey'), 'code_embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'code_embeddings', 'repositories', ['repository_id'], ['id'])
    op.alter_column('github_accounts', 'access_token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.drop_index(op.f('ix_github_accounts_id'), table_name='github_accounts')
    op.drop_index(op.f('ix_github_accounts_user_id'), table_name='github_accounts')
    op.create_index(op.f('ix_github_accounts_user_id'), 'github_accounts', ['user_id'], unique=False)
    op.drop_index(op.f('ix_pull_requests_github_pr_id'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_id'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_repository_id'), table_name='pull_requests')
    op.drop_constraint(op.f('pull_requests_repository_id_fkey'), 'pull_requests', type_='foreignkey')
    op.create_foreign_key(None, 'pull_requests', 'repositories', ['repository_id'], ['id'])
    op.drop_index(op.f('ix_repositories_github_account_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_github_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_owner'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_user_id'), table_name='repositories')
    op.drop_constraint(op.f('repositories_github_account_id_fkey'), 'repositories', type_='foreignkey')
    op.drop_constraint(op.f('repositories_user_id_fkey'), 'repositories', type_='foreignkey')
    op.create_foreign_key(None, 'repositories', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'repositories', 'github_accounts', ['github_account_id'], ['id'])
    op.drop_index(op.f('ix_review_comments_id'), table_name='review_comments')
    op.drop_index(op.f('ix_review_comments_review_id'), table_name='review_comments')
    op.drop_constraint(op.f('review_comments_review_id_fkey'), 'review_comments', type_='foreignkey')
    op.create_foreign_key(None, 'review_comments', 'reviews', ['review_id'], ['id'])
    op.alter_column('review_findings', 'line',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_review_findings_id'), table_name='review_findings')
    op.add_column('reviews', sa.Column('context_budget', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_pull_request_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_repository_id'), table_name='reviews')
    op.drop_constraint(op.f('reviews_pull_request_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_repository_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'pull_requests', ['pull_request_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'repositories', ['repository_id'], ['id'])
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_constraint(op.f('user_settings_user_id_fkey'), 'user_settings', type_='foreignkey')
    op.create_foreign_key(None, 'user_settings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_settings', type_='foreignkey')
    op.create_foreign_key(op.f('user_settings_user_id_fkey'), 'user_settings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_repository_id_fkey'), 'reviews', 'repositories', ['repository_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('reviews_pull_request_id_fkey'), 'reviews', 'pull_requests', ['pull_request_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_reviews_repository_id'), 'reviews', ['repository_id'], unique=False)
    op.create_index(op.f('ix_reviews_pull_request_id'), 'reviews', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.drop_column('reviews', 'context_budget')
    op.create_index(op.f('ix_review_findings_id'), 'review_findings', ['id'], unique=False)
    op.alter_column('review_findings', 'line',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'review_comments', type_='foreignkey')
    op.create_foreign_key(op.f('review_comments_review_id_fkey'), 'review_comments', 'reviews', ['review_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_review_comments_review_id'), 'review_comments', ['review_id'], unique=False)
    op.create_index(op.f('ix_review_comments_id'), 'review_comments', ['id'], unique=False)
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.create_foreign_key(op.f('repositories_user_id_fkey'), 'repositories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('repositories_github_account_id_fkey'), 'repositories', 'github_accounts', ['github_account_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_repositories_user_id'), 'repositories', ['user_id'], unique=False)
    op.create_index(op.f('ix_repositories_owner'), 'repositories', ['owner'], unique=False)
    op.create_index(op.f('ix_repositories_id'), 'repositories', ['id'], unique=False)
    op.create_index(op.f('ix_repositories_github_id'), 'repositories', ['github_id'], unique=True)
    op.create_index(op.f('ix_repositories_github_account_id'), 'repositories', ['github_account_id'], unique=False)
    op.drop_constraint(None, 'pull_requests', type_='foreignkey')
    op.create_foreign_key(op.f('pull_requests_repository_id_fkey'), 'pull_requests', 'repositories', ['repository_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_pull_requests_repository_id'), 'pull_requests', ['repository_id'], unique=False)
    op.create_index(op.f('ix_pull_requests_id'), 'pull_requests', ['id'], unique=False)
    op.create_index(op.f('ix_pull_requests_github_pr_id'), 'pull_requests', ['github_pr_id'], unique=False)
    op.drop_index(op.f('ix_github_accounts_user_id'), table_name='github_accounts')
    op.create_index(op.f('ix_github_accounts_user_id'), 'github_accounts', ['user_id'], unique=True)
    op.create_index(op.f('ix_github_accounts_id'), 'github_accounts', ['id'], unique=False)
    op.alter_column('github_accounts', 'access_token',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'code_embeddings', type_='foreignkey')
    op.create_foreign_key(op.f('code_embeddings_repository_id_fkey'), 'code_embeddings', 'repositories', ['repository_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_code_embeddings_repository_id'), 'code_embeddings', ['repository_id'], unique=False)
    op.create_index(op.f('ix_code_embeddings_id'), 'code_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_code_embeddings_file_path'), 'code_embeddings', ['file_path'], unique=False)
    op.create_index(op.f('ix_code_embeddings_content_hash'), 'code_embeddings', ['content_hash'], unique=False)
    op.drop_constraint(None, 'analysis_jobs', type_='foreignkey')
    op.drop_constraint(None, 'analysis_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('analysis_jobs_review_id_fkey'), 'analysis_jobs', 'reviews', ['review_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('analysis_jobs_repository_id_fkey'), 'analysis_jobs', 'repositories', ['repository_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_analysis_jobs_review_id'), 'analysis_jobs', ['review_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_repository_id'), 'analysis_jobs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_id'), 'analysis_jobs', ['id'], unique=False)
    # ### end Alembic commands ###
